# Generated by Django 4.1.3 on 2022-11-24 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('gravedad', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'Automóvil',
                'verbose_name_plural': 'Automóviles',
                'db_table': 'automoviles',
                'managed': True,
            },
        ),
    ]
